== In the Matter of Nexo Capital Inc. ==

[quote, In the matter of Nexo Capital Inc. Release No. 11149 / January 19&comma; 2023,  https://www.sec.gov/litigation/admin/2023/33-11149.pdf ]
____
[.text-center]
*UNITED STATES OF AMERICA +
Before the +
SECURITIES AND EXCHANGE COMMISSION*

*SECURITIES ACT OF 1933 +
Release No. 11149 / January 19, 2023 +
&nbsp; +
ADMINISTRATIVE PROCEEDING +
File No. 3-21281*

[cols="1a,1a", width=100%, frame=none, grid=none]
|===
|&nbsp; +
*In the Matter of +
&nbsp; +
Nexo Capital Inc., +
&nbsp; +
Respondent. +
&nbsp;* 
|&nbsp; +
&nbsp; +
*ORDER INSTITUTING CEASE-AND-DESIST PROCEEDINGS PURSUANT TO SECTION 8A OF THE SECURITIES ACT OF 1933, MAKING FINDINGS, AND IMPOSING A CEASE-AND-DESIST ORDER*
|===

[.text-center]
[upperroman, start=1]
. &nbsp;

The Securities and Exchange Commission (“Commission”) deems it appropriate that public cease-and-desist proceedings be, and hereby are, instituted pursuant to Section 8A of the Securities Act of 1933 (“Securities Act”) against Nexo Capital Inc. (“Nexo” or “Respondent”).

[.text-center]
[upperroman, start=2]
. &nbsp;

In anticipation of the institution of these proceedings, Respondent has submitted an Offer of Settlement (the “Offer”) which the Commission has determined to accept. Solely for the purpose of these proceedings and any other proceedings brought by or on behalf of the Commission, or to which the Commission is a party, and without admitting or denying the findings herein, except as to the Commission’s jurisdiction over it and the subject matter of these proceedings, which are admitted, Respondent consents to the entry of this Order Instituting Cease-and-Desist Proceedings Pursuant to Section 8A of the Securities Act, Making Findings, and Imposing a Cease-And-Desist Order (“Order”), as set forth below.

[.text-center]
[upperroman, start=3]
. &nbsp;

On the basis of this Order and Respondent’s Offer, the Commission finds that:

[.text-center]
*[underline]#Summary#*

. In or around June 2020, Nexo Capital Inc. (“Nexo”) began to offer and sell the so-called Nexo Earn Interest Product (“EIP”) in the United States. The EIP allowed United States investors to tender to Nexo certain crypto assets, which Nexo deposited in interest- yielding accounts and then used in various ways to generate income for its own business and to fund interest payments to EIP investors. These included staking, lending, and engaging in arbitrage on purportedly “decentralized” finance platforms; investing in certain crypto assets; loaning funds to retail and institutional borrowers; and entering into options and swap contracts with respect to the crypto assets tendered. As of March 2022, Nexo’s EIP had approximately 112,000 U.S. investors and $2.7 billion in assets from U.S. investors.
. Based on the facts and circumstances set forth below, Nexo offered and sold securities in the form of investment contracts and notes. Nexo offered and sold the EIP to a broad segment of the general public to obtain crypto assets for general use in its business. Nexo obtained the crypto assets in exchange for a promise to pay them back, with interest. Investors in the EIP had a reasonable expectation of obtaining a future profit from Nexo’s efforts in managing the EIP, including based on Nexo’s statements about how the EIP was a tool investors could use to generate wealth. Investors also had a reasonable expectation that Nexo would use the invested crypto assets in Nexo’s lending and principal investing activity, and that investors would share profits in the form of interest payments in direct proportion to their investments, as a result of Nexo’s managerial and entrepreneurial efforts. Notably, Nexo promoted the EIP as an investment, by which investors could earn a consistent return. Nexo took complete control over investors’ assets from the EIP, pooled them together, including with Nexo’s other assets, and then deployed those assets in various revenue- generating activities. Additionally, Nexo’s lending and investment activities were at its own discretion, and Nexo was responsible for managing the risks involved.
. Nexo offered and sold securities without a registration statement filed or in effect with the Commission and without qualifying for an exemption from registration. As a result, Nexo violated Sections 5(a) and 5(c) of the Securities Act.

[.text-center]
*[underline]#Respondent#*

[start=4]
. Nexo Capital Inc. (“Nexo”) is a Cayman Islands corporation formed in 2018 with its principal place of business in Grand Cayman, Cayman Islands. Nexo provides crypto asset-related financial products and services, including purchasing, lending, borrowing, trading, and storing. Nexo is part of the Nexo Group, which is comprised of other Nexo entities that are primarily incorporated in various European countries.

[.text-center]
*[underline]#Facts#*

[start=5]
. Since 2018, Nexo has conducted a crypto asset business globally and in the United States through Nexo’s public website http://www.nexo.io and through a mobile application, both of which were accessible at all relevant times from within the United States. The business has included crypto asset-related financial products and services, including the EIP (discussed further below); the “Borrow Product,” by which customers could borrow crypto assets; the “Nexo Exchange,” through which customers could trade certain crypto assets; and storage for crypto assets. As of March 2022, Nexo had 3.7 million global users and $13.7 billion in global assets across its entire platform for the various services it offered.
. In or around June 2020, Nexo began to offer and sell the EIP in the United States. To invest in the EIP, investors provided crypto assets to Nexo in exchange for Nexo’s promise to provide a variable interest payment. Per its description to investors, Nexo determined the interest rate based upon, among other things, the specific crypto asset provided to Nexo by the investor and the duration of time the investor committed to maintaining the asset with Nexo. The longer the time period, the higher the interest rate. Investors began accruing interest 24 hours after tendering eligible crypto assets, with interest calculated daily and compounded for interest earned in-kind.
. Nexo offered the EIP under flexible and fixed terms. Under flexible terms, there was no holding period and investors could withdraw their crypto assets and earned interest at any time. Under fixed terms, investors were unable to withdraw their crypto assets and interest for the duration of the defined term. Interest accrued in connection with the EIP was credited to investors’ accounts at the expiration of the fixed term, if applicable, or otherwise daily. Investors were able to withdraw all or part of the crypto assets they invested with Nexo, including the interest earned, by instructing Nexo to transfer the crypto assets to the investor’s personal “digital wallet” (generally, a unique address within a cryptographically-secured ledger used to “hold” crypto assets) or by instructing Nexo to sell the relevant crypto assets in exchange for fiat currency such as U.S. Dollars, and then transferring the U.S. Dollar proceeds to a selected bank account.
. The investor assets tendered through the EIP were for Nexo’s general use in its business, namely in lending and investment activities, which generated income for Nexo and its investors. Nexo pooled the loaned assets from the EIP together with other Nexo assets and exercised full discretion over how to use the pooled assets. Nexo retained possession and control over the tendered crypto assets.
. The Terms and Conditions for the EIP provided the following:
[none]
.. [Investors] understand and agree that we might convert, pledge, re-pledge, hypothecate, rehypothecate, sell, lend, or otherwise transfer, dispose of or use any amount of any Digital Assets in regard to which you use the Nexo Earn Interest Product, separately or together with other property, and for any period of time, and without retaining in our possession and/or control for delivery a like amount thereof or any other assets, at our sole and absolute discretion. Any such action will be performed in our name only and you will have no benefits and liabilities from it.
. Nexo pooled the assets tendered through the EIP with other assets, and used the asset pool to engage in various revenue-generating activities, including staking, lending, arbitrage, and earning interest on certain purportedly “decentralized” finance platforms by providing liquidity; investing in certain crypto assets; offering crypto credit lines (i.e., loans to retail and institutional borrowers); and entering into options and swap contracts. Nexo relied on the revenue generated from the foregoing activities to fund interest payments to EIP investors and to generate income and profits for Nexo itself.
. Nexo marketed the EIP to U.S. investors through general solicitations on its website, the Nexo mobile application, and on social media and elsewhere online, including on Facebook, LinkedIn, and Twitter. Nexo promoted the EIP as an investment and profit-making opportunity. For example, Nexo advertised the attractive interest rates offered through the EIP as a way to “grow your wealth.” It highlighted on its website that investors could earn “up to 12% annual interest.” Nexo also promoted the EIP as an investment opportunity on Twitter. For example, in a March 30, 2021 tweet, titled “Why Nexo #1: HODLing [sic]+ Growing Your Investments,” Nexo linked to additional information on its website to “Learn how to earn compounding interest on your Crypto and Fiat assets using Nexo’s Savings Account.” xref:sec_nexo_footnote_1[^*(1)*^]
. At no point has Nexo or any other entity in the Nexo Group filed a registration statement with the Commission for the offer and sale of the EIP. Nor did the offer and sale of the EIP qualify for an exemption from registration under the Securities Act. The only registrations that Nexo Group entities have with U.S.-based regulators are money transmitter licenses and certain state-level consumer or lender licenses.
. Under the EIP Terms and Conditions “Risk Disclosure” section, which is available on Nexo’s website, Nexo explained that “Digital Assets are not money or legal tender, are not backed by the government or by a central bank and mostly do not have any underlying assets, revenue stream, or another source of value.” Another provision under the Risk Disclosure section provides:
[none]
.. You understand and agree that you use the Nexo Account and the Nexo Earn Interest Product at your own risk. This section is not exhaustive and does not disclose all the risks associated with the Digital Assets and the use of the Nexo Earn Interest Product and any of the related Nexo Wallet Services. You shall, therefore, carefully
consider whether such use is suitable for you in light of your circumstances and financial resources.
. On February 18, 2022, after the Commission announced charges with respect to a crypto investment product similar to the EIP, see BlockFi Lending LLC, Exch. Act Rel. No. 11029 (Feb. 14, 2022), Nexo voluntarily ceased offering and selling the EIP to new U.S. investors. After February 18, 2022, existing U.S. investors continued to earn interest (at varying rates) on assets held in EIP accounts as of that date, but assets added after that date would not earn interest. In early March 2022, just as Nexo put in place these restrictions for U.S. investors, there were approximately 440,000 global investors in the EIP and 112,000 investors in the U.S. As of March 2022, the value of EIP assets was approximately $9 billion globally and $2.7 billion in the U.S.
. On December 5, 2022, Nexo proactively announced that it was terminating the EIP in certain states and “phasing out” all of its products and services in the United States, including permanently ceasing to offer and sell the EIP to U.S. investors, and winding down the EIP for existing U.S. investors who continued to earn interest on funds held in the EIP prior to February 18, 2022.

[.text-center]
*[underline]#Legal Analysis#*

[start=16]
. The Securities Act and the Securities Exchange Act of 1934 (“Exchange Act”) were designed to “eliminate serious abuses in a largely unregulated securities market.” United Housing Found., Inc. v. Forman, 421 U.S. 837, 849 (1975). They are focused, among other things, “on the capital market of the enterprise system: the sale of securities to raise capital for profit-making purposes . . . and the need for regulation to prevent fraud and to protect the interest of investors.” Id. Under Section 2(a)(1) of the Securities Act, a security includes any “note.” See 15 U.S.C. §§ 77b. A note is presumed to be a security unless it bears a strong resemblance, to instruments that are not securities, which courts determine by examining four factors: (1) the motivation of the parties; (2) the plan of distribution; (3) the expectations of the investing public; and (4) a risk-reducing factor such as the availability of an alternative regulatory regime that “significantly reduces the risk of the instrument, thereby rendering application of the Securities Acts unnecessary.” See Reves, 494 U.S. at 64–66.
. Applying the Reves four-part analysis, the EIPs were securities. First, Nexo offered and sold the EIP to obtain crypto assets for the general use of its business, namely to run its lending and investment activities to pay interest to EIP investors, and purchasers invested in the EIP to receive interest on the loaned crypto assets. Second, the EIP was offered and sold to a broad segment of the general public. Third, Nexo promoted the EIP as an investment, specifically as a way to earn a consistent return on crypto assets. Fourth, no alternative regulatory scheme or other risk-reducing factors exist with respect to the EIP.
. Under Section 2(a)(1) of the Securities Act, a security includes “an investment contract.” See 15 U.S.C. §§ 77b. Based on the facts set forth above, the EIP also constitutes the offer and sale of investment contracts. See Howey, 328 U.S. at 301. Investors in the EIP tendered money to Nexo, in the form of crypto assets, to participate in the EIP. Nexo then pooled the EIP investors’ crypto assets and used those assets for lending and investment activities that would generate returns for both Nexo and EIP investors. The returns earned by each EIP investor were a function of the pooling of the loaned crypto assets, and the ways in which Nexo deployed those loaned assets. In this way, each investor’s fortune was tied to the fortunes of the other investors. In addition, because Nexo earned revenue for itself through its deployment of the loaned assets, the EIP investors’ fortunes were also linked to those of Nexo. Moreover, EIP investors’ return were based on interest rates and proportional to their investments in EIP. Through its public statements, Nexo created a reasonable expectation that EIP investors would earn profits derived from Nexo’s efforts to manage the loaned crypto assets profitably enough to pay the stated interest rates to the investors. Nexo retained ownership and control over the borrowed crypto assets, and determined how much to hold, lend, and invest. Nexo’s lending and investment activities were at its own discretion, and Nexo managed the risks involved.
. Nexo did not file a registration statement with the Commission for the offers and sales of EIP, nor did its offers and sales of the EIP qualify for an exemption from registration under the Securities Act. 
. As a result of the conduct described above, Nexo violated Section 5(a) of the Securities Act, which prohibits, unless a registration statement is in effect as to a security, any person, directly or indirectly, from making use of any means or instruments of transportation or communication in interstate commerce or of the mails to sell such security through the use or medium of any prospectus or otherwise; or to carry or cause to be carried through the mails or in interstate commerce, by any means or instruments of transportation, any such security for the purpose of sale or for delivery after sale.
. As a result of the conduct described above, Nexo also violated Section 5(c) of the Securities Act, which prohibits any person, directly or indirectly, from making use of any means or instruments of transportation or communication in interstate commerce or of the mails to offer to sell or offer to buy through the use or medium of any prospectus or otherwise any security, unless a registration statement has been filed as to such security.

[.text-center]
*[underline]#Respondent’s Cooperation and Remedial Efforts#*

[start=22]
. As explained above, on February 18, 2022, after the Commission announced charges involving a similar crypto investment product, Nexo voluntarily ceased offering the EIP to new U.S. investors and ceased paying interest on new funds added to existing EIP accounts of U.S. investors. On December 5, 2022, Nexo proactively announced that it was ceasing the EIP in certain states and phasing out all of its products and services in the United States, including permanently ceasing to offer the EIP to all U.S. investors.
. Nexo will cease the EIP as to all U.S. investors by April 1, 2023 and will exit the U.S. entirely shortly thereafter.
. Nexo will maintain the interest rate that is in place as of the date of the entry of this Order on existing U.S. EIP accounts for the duration of the period of time that Nexo takes to phase out all of its products and services in the United States.
. In determining to accept the Offer, the Commission considered remedial acts promptly undertaken by Respondent and cooperation afforded the Commission staff.

[.text-center]
[upperroman, start=4]
. &nbsp;

In view of the foregoing, the Commission deems it appropriate and in the public interest to
impose the sanctions agreed to in Respondent’s Offer.

Accordingly, it is hereby ORDERED that:

[upperalpha]
. Pursuant to Section 8A of the Securities Act, Respondent cease and desist from committing or causing any violations and any future violations of Sections 5(a) and 5(c) of the Securities Act.
. Respondent shall pay a civil money penalty in the amount of $22,500,000.00 to the Securities and Exchange Commission for transfer to the general fund of the United States Treasury, subject to Exchange Act Section 21F(g)(3). Payment shall be made in the following installments:
[numeric]
.. Due within 14 days of the entry of this Order: $7,500,000
.. Due within 120 days of the entry of this Order: $5,000,000
.. Due within 240 days of the entry of this Order: $5,000,000
.. Due within 365 days of the entry of this Order: $5,000,000 

[none]
. Payments shall be applied first to post-order interest, which accrues pursuant to 31 U.S.C. § 3717. Prior to making the final payment set forth herein, Respondent shall contact the staff of the Commission for the amount due. If Respondent fails to make any payment by the date agreed and/or in the amount agreed according to the schedule set forth above, all outstanding payments under this Order, including post-order interest, minus any payments made, shall become due and payable immediately at the discretion of the staff of the Commission without further application to the Commission.
. Payment must be made in one of the following ways:
[numeric]
.. Respondent may transmit payment electronically to the Commission, which will provide detailed ACH transfer/Fedwire instructions upon request;
.. Respondent may make direct payment from a bank account via Pay.gov through the SEC website at http://www.sec.gov/about/offices/ofm.htm; or
.. Respondent may pay by certified check, bank cashier’s check, or United States postal money order, made payable to the Securities and Exchange Commission and hand-delivered or mailed to:
[none]
... Enterprise Services Center +
Accounts Receivable Branch +
HQ Bldg., Room 181, AMZ-341 +
6500 South MacArthur Boulevard +
Oklahoma City, OK 73169

[none]
. Payments by check or money order must be accompanied by a cover letter identifying Nexo Capital Inc. as Respondent in these proceedings, and the file number of these proceedings; a copy of the cover letter and check or money order must be sent to Stacy Bogert, Division of Enforcement, Securities and Exchange Commission, 100 F St., NE, Washington, DC 20549.

[upperalpha, start=3]
. Amounts ordered to be paid as civil money penalties pursuant to this Order shall be treated as penalties paid to the government for all purposes, including all tax purposes. To preserve the deterrent effect of the civil penalty, Respondent agrees that in any Related Investor Action, they shall not argue that they are entitled to, nor shall they benefit by, offset or reduction of any award of compensatory damages by the amount of any part of Respondent’s payment of a civil penalty in this action (“Penalty Offset”). If the court in any Related Investor Action grants such a Penalty Offset, Respondent agrees that it shall, within 30 days after entry of a final order granting the Penalty Offset, notify the Commission's counsel in this action and pay the amount of the Penalty Offset to the Securities and Exchange Commission. Such a payment shall not be deemed an additional civil penalty and shall not be deemed to change the amount of the civil penalty imposed in this proceeding. For purposes of this paragraph, a “Related Investor Action” means a private damages action brought against Respondent by or on behalf of one or more investors based on substantially the same facts as alleged in the Order instituted by the Commission in this proceeding.

[cols="1a,1a", width=100%, frame=none, grid=none]
|===
|By the Commission.
| &nbsp; +
&nbsp; +
&nbsp; +
Vanessa A. Countryman +
Secretary
|===
[[sec_nexo_footnote_1]]
[1] “HODL” is a term used by participants in the crypto markets that means “Hold On for Dear Life,” presumably as an allusion to the high volatility that is inherent in the prices of many crypto assets. HODL is also used to describe a commitment to retain, rather than sell, crypto assets once acquired, and may derive from a misspelling of “hold.”
____


=== Discussion Questions ===
. what should the question be?