[[Introduction]]
== Introduction ==

[.text-justify]
This book is intended as a textbook for a semester-length course on cryptocurrency law in the United States of America.  The textbook is intended for law students or graduate students studying cryptocurrency.  his book examines how Judges are applying U.S. Laws and Regulations to factual events involving Cryptocurrency. This book is designed as a casebook for students who wish to study U.S. cryptocurrency law. Our plan is to release an updated version of this book every year.

[.text-justify]
The focus of the textbook is on cryptocurrency law, and other topics should be supplemented by the instructor as necessary.  If students need additional background materials on cryptocurrency technology, those topics are not covered in this book, but I do provide references to additional materials.  If students need additional background on some of the legal topics, I also provide references for those additional topics.
[.text-justify]
If students have not previously been exposed to cryptocurrency, the instructor should consider beginning with an overview of Bitcoin, Ethereum, and Decentralized Finance before diving into the topics covered by the Cryptocurrency Regulation textbook.

[.text-justify]
About the author:  Thomas Plunkett has given hundreds of lectures on topics related to cryptocurrency. He has a Master of Science in Blockchain and Digital Currency from the University of Nicosia.  He has a Master of Science in Computer Science from Virginia Tech.  He has taken graduate courses in Cryptogrpahy, Blockchain, and other engineering topics from Stanford University.  He has a B.A. and a J.D. from George Mason University.  He is admitted to the Virginia State Bar and the Patent Bar.  
