= Securities Exchange Commission =


== Digital Asset Transactions: When Howey Met Gary (Plastic) ==

[quote, William Hinman, "Digital Asset Transactions: When Howey Met Gary (Plastic)". 2018]
____
*Remarks at the Yahoo Finance All Markets Summit: Crypto*
footnote:[Hinman, William. "Digital Asset Transactions: When Howey Met Gary (Plastic)." URL: https://www.sec.gov/news/speech/speech-hinman-061418 (2018).]

Thank you Andy. I am pleased to be here today. This event provides a great opportunity to address a topic that is the subject of considerable debate in the press and in the crypto-community -- whether a digital asset offered as a security can, over time, become something other than a security.

To start, we should frame the question differently and focus not on the digital asset itself, but on the circumstances surrounding the digital asset and the manner in which it is sold. To that end, a better line of inquiry is: “Can a digital asset that was originally offered in a securities offering ever be later sold in a manner that does not constitute an offering of a security?” In cases where the digital asset represents a set of rights that gives the holder a financial interest in an enterprise, the answer is likely “no.” In these cases, calling the transaction an initial coin offering, or “ICO,” or a sale of a “token,” will not take it out of the purview of the U.S. securities laws.

But what about cases where there is no longer any central enterprise being invested in or where the digital asset is sold only to be used to purchase a good or service available through the network on which it was created? I believe in these cases the answer is a qualified “yes.” I would like to share my thinking with you today about the circumstances under which that could occur.

Before I turn to the securities law analysis, let me share what I believe may be most exciting about distributed ledger technology -- that is, the potential to share information, transfer value, and record transactions in a decentralized digital environment. Potential applications include supply chain management, intellectual property rights licensing, stock ownership transfers and countless others. There is real value in creating applications that can be accessed and executed electronically with a public, immutable record and without the need for a trusted third party to verify transactions. Some people believe that this technology will transform e-commerce as we know it. There is excitement and a great deal of speculative interest around this new technology. Unfortunately, there also are cases of fraud. In many regards, it is still “early days.”

But I am not here to discuss the promise of technology -- there are many in attendance and speaking here today that can do a much better job of that. I would like to focus on the application of the federal securities laws to digital asset transactions -- that is how tokens and coins are being issued, distributed and sold. While perhaps a bit dryer than the promise of the blockchain, this topic is critical to the broader acceptance and use of these novel instruments.

I will begin by describing what I often see. Promoters, in order to raise money to develop networks on which digital assets will operate, often sell the tokens or coins rather than sell shares, issue notes or obtain bank financing. But, in many cases, the economic substance is the same as a conventional securities offering. Funds are raised with the expectation that the promoters will build their system and investors can earn a return on the instrument -- usually by selling their tokens in the secondary market once the promoters create something of value with the proceeds and the value of the digital enterprise increases.

When we see that kind of economic transaction, it is easy to apply the Supreme Court's “investment contract” test first announced in SEC v. Howey. That test requires an investment of money in a common enterprise with an expectation of profit derived from the efforts of others. And it is important to reflect on the facts of Howey. A hotel operator sold interests in a citrus grove to its guests and claimed it was selling real estate, not securities. While the transaction was recorded as a real estate sale, it also included a service contract to cultivate and harvest the oranges. The purchasers could have arranged to service the grove themselves but, in fact, most were passive, relying on the efforts of Howey-in-the-Hills Service, Inc. for a return. In articulating the test for an investment contract, the Supreme Court stressed: “Form [is] disregarded for substance and the emphasis [is] placed upon economic reality.” So the purported real estate purchase was found to be an investment contract -- an investment in orange groves was in these circumstances an investment in a security.

Just as in the Howey case, tokens and coins are often touted as assets that have a use in their own right, coupled with a promise that the assets will be cultivated in a way that will cause them to grow in value, to be sold later at a profit. And, as in Howey -- where interests in the groves were sold to hotel guests, not farmers -- tokens and coins typically are sold to a wide audience rather than to persons who are likely to use them on the network.

In the ICOs I have seen, overwhelmingly, promoters tout their ability to create an innovative application of blockchain technology. Like in Howey, the investors are passive. Marketing efforts are rarely narrowly targeted to token users. And typically at the outset, the business model and very viability of the application is still uncertain. The purchaser usually has no choice but to rely on the efforts of the promoter to build the network and make the enterprise a success. At that stage, the purchase of a token looks a lot like a bet on the success of the enterprise and not the purchase of something used to exchange for goods or services on the network.

As an aside, you might ask, given that these token sales often look like securities offerings, why are the promoters choosing to package the investment as a coin or token offering? This is an especially good question if the network on which the token or coin will function is not yet operational. I think there can be a number of reasons. For a while, some believed such labeling might, by itself, remove the transaction from the securities laws. I think people now realize labeling an investment opportunity as a coin or token does not achieve that result. Second, this labeling might have been used to bring some marketing “sizzle” to the enterprise. That might still work to some extent, but the track record of ICOs is still being sorted out and some of that sizzle may now be more of a potential warning flare for investors.

Some may be attracted to a blockchain-mediated crowdfunding process. Digital assets can represent an efficient way to reach a global audience where initial purchasers have a stake in the success of the network and become part of a network where their participation adds value beyond their investment contributions. The digital assets are then exchanged -- for some, to help find the market price for the new application; for others, to speculate on the venture. As I will discuss, whether a transaction in a coin or token on the secondary market amounts to an offer or sale of a security requires a careful and fact-sensitive legal analysis.

I believe some industry participants are beginning to realize that, in some circumstances, it might be easier to start a blockchain-based enterprise in a more conventional way. In other words, conduct the initial funding through a registered or exempt equity or debt offering and, once the network is up and running, distribute or offer blockchain-based tokens or coins to participants who need the functionality the network and the digital assets offer. This allows the tokens or coins to be structured and offered in a way where it is evident that purchasers are not making an investment in the development of the enterprise.

Returning to the ICOs I am seeing, strictly speaking, the token -- or coin or whatever the digital information packet is called -- all by itself is not a security, just as the orange groves in Howey were not. Central to determining whether a security is being sold is how it is being sold and the reasonable expectations of purchasers. When someone buys a housing unit to live in, it is probably not a security. But under certain circumstances, the same asset can be offered and sold in a way that causes investors to have a reasonable expectation of profits based on the efforts of others. For example, if the housing unit is offered with a management contract or other services, it can be a security. Similarly, when a CD, exempt from being treated as a security under Section 3 of the Securities Act, is sold as a part of a program organized by a broker who offers retail investors promises of liquidity and the potential to profit from changes in interest rates, the Gary Plastic case teaches us that the instrument can be part of an investment contract that is a security.

The same reasoning applies to digital assets. The digital asset itself is simply code. But the way it is sold -- as part of an investment; to non-users; by promoters to develop the enterprise -- can be, and, in that context, most often is, a security -- because it evidences an investment contract. And regulating these transactions as securities transactions makes sense. The impetus of the Securities Act is to remove the information asymmetry between promoters and investors. In a public distribution, the Securities Act prescribes the information investors need to make an informed investment decision, and the promoter is liable for material misstatements in the offering materials. These are important safeguards, and they are appropriate for most ICOs. The disclosures required under the federal securities laws nicely complement the Howey investment contract element about the efforts of others. As an investor, the success of the enterprise -- and the ability to realize a profit on the investment -- turns on the efforts of the third party. So learning material information about the third party -- its background, financing, plans, financial stake and so forth -- is a prerequisite to making an informed investment decision. Without a regulatory framework that promotes disclosure of what the third party alone knows of these topics and the risks associated with the venture, investors will be uninformed and are at risk.

But this also points the way to when a digital asset transaction may no longer represent a security offering. If the network on which the token or coin is to function is sufficiently decentralized -- where purchasers would no longer reasonably expect a person or group to carry out essential managerial or entrepreneurial efforts -- the assets may not represent an investment contract. Moreover, when the efforts of the third party are no longer a key factor for determining the enterprise's success, material information asymmetries recede. As a network becomes truly decentralized, the ability to identify an issuer or promoter to make the requisite disclosures becomes difficult, and less meaningful.

And so, when I look at Bitcoin today, I do not see a central third party whose efforts are a key determining factor in the enterprise. The network on which Bitcoin functions is operational and appears to have been decentralized for some time, perhaps from inception. Applying the disclosure regime of the federal securities laws to the offer and resale of Bitcoin would seem to add little value. And putting aside the fundraising that accompanied the creation of Ether, based on my understanding of the present state of Ether, the Ethereum network and its decentralized structure, current offers and sales of Ether are not securities transactions. And, as with Bitcoin, applying the disclosure regime of the federal securities laws to current transactions in Ether would seem to add little value. Over time, there may be other sufficiently decentralized networks and systems where regulating the tokens or coins that function on them as securities may not be required. And of course there will continue to be systems that rely on central actors whose efforts are a key to the success of the enterprise. In those cases, application of the securities laws protects the investors who purchase the tokens or coins.

I would like to emphasize that the analysis of whether something is a security is not static and does not strictly inhere to the instrument. Even digital assets with utility that function solely as a means of exchange in a decentralized network could be packaged and sold as an investment strategy that can be a security. If a promoter were to place Bitcoin in a fund or trust and sell interests, it would create a new security. Similarly, investment contracts can be made out of virtually any asset (including virtual assets), provided the investor is reasonably expecting profits from the promoter's efforts.

Let me emphasize an earlier point: simply labeling a digital asset a “utility token” does not turn the asset into something that is not a security. I recognize that the Supreme Court has acknowledged that if someone is purchasing an asset for consumption only, it is likely not a security. But, the economic substance of the transaction always determines the legal analysis, not the labels. The oranges in Howey had utility. Or in my favorite example, the Commission warned in the late 1960s about investment contracts sold in the form of whisky warehouse receipts. Promoters sold the receipts to U.S. investors to finance the aging and blending processes of Scotch whisky. The whisky was real -- and, for some, had exquisite utility. But Howey was not selling oranges and the warehouse receipts promoters were not selling whisky for consumption. They were selling investments, and the purchasers were expecting a return from the promoters' efforts.

Promoters and other market participants need to understand whether transactions in a particular digital asset involve the sale of a security. We are happy to help promoters and their counsel work through these issues. We stand prepared to provide more formal interpretive or no-action guidance about the proper characterization of a digital asset in a proposed use. In addition, we recognize that there are numerous implications under the federal securities laws of a particular asset being considered a security. For example, our Divisions of Trading and Markets and Investment Management are focused on such issues as broker-dealer, exchange and fund registration, as well as matters of market manipulation, custody and valuation. We understand that market participants are working to make their services compliant with the existing regulatory framework, and we are happy to continue our engagement in this process.

What are some of the factors to consider in assessing whether a digital asset is offered as an investment contract and is thus a security? Primarily, consider whether a third party -- be it a person, entity or coordinated group of actors -- drives the expectation of a return. That question will always depend on the particular facts and circumstances, and this list is illustrative, not exhaustive:

    . Is there a person or group that has sponsored or promoted the creation and sale of the digital asset, the efforts of whom play a significant role in the development and maintenance of the asset and its potential increase in value?
    . Has this person or group retained a stake or other interest in the digital asset such that it would be motivated to expend efforts to cause an increase in value in the digital asset? Would purchasers reasonably believe such efforts will be undertaken and may result in a return on their investment in the digital asset?
    . Has the promoter raised an amount of funds in excess of what may be needed to establish a functional network, and, if so, has it indicated how those funds may be used to support the value of the tokens or to increase the value of the enterprise? Does the promoter continue to expend funds from proceeds or operations to enhance the functionality and/or value of the system within which the tokens operate?
    . Are purchasers “investing,” that is seeking a return? In that regard, is the instrument marketed and sold to the general public instead of to potential users of the network for a price that reasonably correlates with the market value of the good or service in the network?
    . Does application of the Securities Act protections make sense? Is there a person or entity others are relying on that plays a key role in the profit-making of the enterprise such that disclosure of their activities and plans would be important to investors? Do informational asymmetries exist between the promoters and potential purchasers/investors in the digital asset?
    . Do persons or entities other than the promoter exercise governance rights or meaningful influence?

While these factors are important in analyzing the role of any third party, there are contractual or technical ways to structure digital assets so they function more like a consumer item and less like a security. Again, we would look to the economic substance of the transaction, but promoters and their counsels should consider these, and other, possible features. This list is not intended to be exhaustive and by no means do I believe each and every one of these factors needs to be present to establish a case that a token is not being offered as a security. This list is meant to prompt thinking by promoters and their counsel, and start the dialogue with the staff -- it is not meant to be a list of all necessary factors in a legal analysis.

. Is token creation commensurate with meeting the needs of users or, rather, with feeding speculation?
. Are independent actors setting the price or is the promoter supporting the secondary market for the asset or otherwise influencing trading?
. Is it clear that the primary motivation for purchasing the digital asset is for personal use or consumption, as compared to investment? Have purchasers made representations as to their consumptive, as opposed to their investment, intent? Are the tokens available in increments that correlate with a consumptive versus investment intent?
. Are the tokens distributed in ways to meet users' needs? For example, can the tokens be held or transferred only in amounts that correspond to a purchaser's expected use? Are there built-in incentives that compel using the tokens promptly on the network, such as having the tokens degrade in value over time, or can the tokens be held for extended periods for investment?
. Is the asset marketed and distributed to potential users or the general public?
. Are the assets dispersed across a diverse user base or concentrated in the hands of a few that can exert influence over the application?
. Is the application fully functioning or in early stages of development?


These are exciting legal times and I am pleased to be part of a process that can help promoters of this new technology and their counsel navigate and comply with the federal securities laws.
____


=== Discussion Questions ===

. What makes a digital asset a security?


== SEC Charges Eleven Individuals in $300 Million Crypto Pyramid Scheme ==
[quote, SEC.gov | SEC Charges Eleven Individuals in $300 Million Crypto Pyramid Scheme. (2022). Retrieved 2 August 2022, from https://www.sec.gov/news/press-release/2022-134]
____
*Alleged Fraudulent Blockchain Scheme Spanned Multiple Countries Including U.S., Russia *
footnote:[SEC.gov | SEC Charges Eleven Individuals in $300 Million Crypto Pyramid Scheme. (2022). Retrieved 2 August 2022, from https://www.sec.gov/news/press-release/2022-134]

FOR IMMEDIATE RELEASE +
2022-134 +
Washington D.C., Aug. 1, 2022 — The Securities and Exchange Commission today charged 11 individuals for their roles in creating and promoting Forsage, a fraudulent crypto pyramid and Ponzi scheme that raised more than $300 million from millions of retail investors worldwide, including in the United States. Those charged include the four founders of Forsage, who were last known to be living in Russia, the Republic of Georgia, and Indonesia, as well as three U.S.-based promoters engaged by the founders to endorse Forsage on its website and social media platforms, and several members of the so-called Crypto Crusaders—the largest promotional group for the scheme that operated in the United States from at least five different states.

According to the SEC’s complaint, in January 2020, Vladimir Okhotnikov, Jane Doe a/k/a Lola Ferrari, Mikhail Sergeev, and Sergey Maslakov launched Forsage.io, a website that allowed millions of retail investors to enter into transactions via smart contracts that operated on the Ethereum, Tron, and Binance blockchains. However, Forsage allegedly has operated as a pyramid scheme for more than two years, in which investors earned profits by recruiting others into the scheme.  Forsage also allegedly used assets from new investors to pay earlier investors in a typical Ponzi structure.

Despite cease-and-desist actions against Forsage for operating as a fraud in September 2020 by the Securities and Exchange Commission of the Philippines and in March 2021 by the Montana Commissioner of Securities and Insurance, the defendants allegedly continued to promote the scheme while denying the claims in several YouTube videos and by other means.

"As the complaint alleges, Forsage is a fraudulent pyramid scheme launched on a massive scale and aggressively marketed to investors," said Carolyn Welshhans, Acting Chief of the SEC’s Crypto Assets and Cyber Unit. "Fraudsters cannot circumvent the federal securities laws by focusing their schemes on smart contracts and blockchains."

In addition to charging the four founders, the complaint, filed in United States District Court in the Northern District of Illinois, also charges Cheri Beth Bowen, of Pelahatchie, Miss., Ronald R. Deering, of Coeur d’ Alene, Idaho, Samuel D. Ellis, of Louisville, Ky., Mark F. Hamlin, of Henrico, Va., Carlos L. Martinez, of Chicago, Ill., Alisha R. Shepperd, of Dunedin, Fla., and Sarah L. Theissen, of Hartford, Wis., with violating the registration and anti-fraud provisions of the federal securities laws. The SEC’s complaint seeks injunctive relief, disgorgement, and civil penalties.

Without admitting or denying the allegations, two of the defendants, Ellis and Theissen, agreed to settle the charges and to be permanently enjoined from future violations of the charged provisions and certain other activity. Additionally, Ellis agreed to pay disgorgement and civil penalties, and Theissen will be required to pay disgorgement and civil penalties as determined by the court. Both settlements are subject to court approval.

The SEC’s investigation was conducted by Liz Canizares and Pamela Sawhney of the Crypto Assets and Cyber Unit and supervised by Amy Friedman and Ms. Welshhans. The litigation is being conducted by Patrick Costello, Christopher Carney, Ms. Canizares, and Ms. Sawhney and supervised by Olivia Choe. The Commission appreciates the assistance of the Securities and Exchange Commission of the Philippines and the Montana Commissioner of Securities and Insurance.

[frame=none, grid=none]
|===
|Foreign Defendants |Last known residence

|Vladimir Okhotnikov 
|Tbilisi, Republic of Georgia

|Jane Doe a/k/a Lola Ferrari 
|Bali, Indonesia

|Mikail Sergeev 
|Moscow, Russia

|Sergey Maslakov 
|Moscow, Russia
|===
____

=== Discussion Questions ===

. Is this a placeholder for dicussion question 1 on the excerpt?