= Department of Justice =



== Former Employee of NFT Marketplace Charged in First Ever Digital Asset Insider Trading Scheme footnote:[Department of Justice U.S. Attorney’s Office Southern District of New York, ‘Former Employee of NFT Marketplace Charged in First Ever Digital Asset Insider Trading Scheme’ (2022) <https://www.justice.gov/usao-sdny/pr/former-employee-nft-marketplace-charged-first-ever-digital-assetinsider-trading-scheme> accessed July 12, 2022] ==


[qoute, Department of Justice U.S. Attorney’s Office Southern District of New York, ‘Former Employee of NFT Marketplace Charged in First Ever Digital Asset Insider Trading Scheme’ (2022) ]

____
*Defendant Allegedly Traded on Inside Information About NFTs That Were Scheduled to be Featured on The Homepage of The Largest NFT Marketplace*

Damian Williams, the United States Attorney for the Southern District of New York, and Michael J. Driscoll, Assistant Director-in-Charge of the New York Field Office of the Federal Bureau of Investigation (“FBI”), announced today the unsealing of an Indictment charging NATHANIEL CHASTAIN, a former product manager at Ozone Networks, Inc. d/b/a OpenSea (“OpenSea”), with wire fraud and money laundering in connection with a scheme to commit insider trading in Non-Fungible Tokens, or “NFTs,” by using confidential information about what NFTs were going to be featured on OpenSea's homepage for his personal financial gain.  CHASTAIN was arrested this morning in New York, New York and will be presented today in the United States District Court for the Southern District of New York.

U.S. Attorney Damian Williams said:  “NFTs might be new, but this type of criminal scheme is not.  As alleged, Nathaniel Chastain betrayed OpenSea by using its confidential business information to make money for himself.  Today's charges demonstrate the commitment of this Office to stamping out insider trading -- whether it occurs on the stock market or the blockchain.”

FBI Assistant Director-in-Charge Michael J. Driscoll said:  “In this case, as alleged, Chastain launched an age-old scheme to commit insider trading by using his knowledge of confidential information to purchase dozens of NFTs in advance of them being featured on OpenSea's homepage. With the emergence of any new investment tool, such as blockchain supported non-fungible tokens, there are those who will exploit vulnerabilities for their own gain. The FBI will continue to aggressively pursue actors who choose to manipulate the market in this way.”

As alleged in the Indictment unsealed today in Manhattan federal court:

This case concerns insider trading in NFTs on OpenSea, the largest online marketplace for the purchase and sale of NFTs. In violation of the duties of trust and confidence he owed to his employer, OpenSea, CHASTAIN exploited his advanced knowledge of what NFTs would be featured on OpenSea's homepage for his personal financial gain.

As part of his employment, CHASTAIN was responsible for selecting NFTs to be featured on OpenSea's homepage. OpenSea kept confidential the identity of featured NFTs until they appeared on its homepage. After an NFT was featured on OpenSea's homepage, the price buyers were willing to pay for that NFT, and for other NFTs made by the same NFT creator, typically increased substantially.

From at least in or about June 2021 to at least in or about September 2021, CHASTAIN used OpenSea's confidential business information about what NFTs were going to be featured on its homepage to secretly purchase dozens of NFTs shortly before they were featured. After those NFTs were featured on OpenSea, CHASTAIN sold them at profits of two- to five-times his initial purchase price. To conceal the fraud, CHASTAIN conducted these purchases and sales using anonymous digital currency wallets and anonymous accounts on OpenSea.

***

CHASTAIN, 31, of New York, New York is charged with one count of wire fraud and one count of money laundering, each of which carries a maximum sentence of 20 years in prison. 

The maximum potential sentences are prescribed by Congress and are provided here for informational purposes only, as any sentencing of the defendant will be determined by a judge.

Mr. Williams praised the outstanding work of the FBI. Mr. Williams also thanked the National Cryptocurrency Enforcement Team for their assistance in the investigation. 

This case is being handled by the Office's Securities and Commodities Fraud Task Force. Assistant U.S. Attorneys Thomas S. Burnett and Nicolas Roos are in charge of the prosecution. 

The charges contained in the Indictment are merely accusations, and the defendant is presumed innocent unless and until proven guilty.
____

=== Discussion Questions ===
. With the need of having a central authority policing fraud, to what extent are decentralization and trustless operations pracitcal?