
= Chapter 1 Bitcoin =

Bitcoin White Paper

Wright vs. McCormack

Chapter 2

= Chapter 3 Initial Coin Offerings and Token Sales =

When Howey Met Gary

SEC Charges Eleven Individuals in $300 Million Crypto Pyramid Scheme

SEC vs. LBRY

In the Matter of Zachary Coburn

Securities and Exchange Commission v. Ellison et al

CoinDeal Charged with Fraud

SEC v. Genesis & Gemini

In the Matter of Nexo Capital Inc.

Payward Ventures and Payward Trading

Terraform & Kwon (Kwonzi Scheme)

= Chapter 4 Cryptocurrency and NFT Insider Trading =

Former Employee of NFT Marketplace Charged in First Ever Digital Asset Insider Trading Scheme

Founder and Majority Owner of Cryptocurrency Exchange Bitzlato Charged

Former Coinbase Insider Pleads Guilty In First-Ever Cryptocurrency Insider Trading Case

= Chapter 5 Currency Mixers =

U.S. Treasury Issues First-Ever Sanctions on a Virtual Currency Mixer, Targets DPRK Cyber Threats

Chapter 6 

Chapter 7 FDIC

Joint Letter Regarding Potential Violations of the Federal Deposit Insurance Act

Chapter 8 CFTC

CFTC v. Bankman-Fried et al.

Chapter 9 Bankruptcy

Celsius Network LLC, et al.

Examiner Report on CELSIUS NETWORK LLC, et al.

Chapter 10 Anti-Money Laundering

Consent Order in the matter of Coinbase, Inc.

Chapter 11 Ethics

ACCEPTING CRYPTOCURRENCY AS AN ADVANCE FEE FOR LEGAL SERVICES


