
= Introduction Chapter =

= Bitcoin Chapter =

Bitcoin White Paper

Wright vs. McCormack

= Pyramid Schemes and Fraud =

CoinDeal Charged with Fraud

SEC Charges Eleven Individuals in $300 Million Crypto Pyramid Scheme


= Initial Coin Offerings, Staking, and Token Sales Chapter =

Report of Investigation Pursuant to Section 21(a) of the Securities Exchange Act of 1934: 
The DAO

In the Matter of Zachary Coburn

When Howey Met Gary

TurnKey Jet No Action Letter

SEC vs. LBRY

SEC v. Genesis & Gemini

In the Matter of Nexo Capital Inc.

Payward Ventures and Payward Trading

Blockfi Lending

= Cryptocurrency and NFT Insider Trading Chapter =

Former Employee of NFT Marketplace Charged in First Ever Digital Asset Insider Trading Scheme

Former Coinbase Insider Pleads Guilty In First-Ever Cryptocurrency Insider Trading Case

= Currency Mixers Chapter =

U.S. Treasury Issues First-Ever Sanctions on a Virtual Currency Mixer, Targets DPRK Cyber Threats

U.S. Treasury Sanctions Notorious Virtual Currency Mixer Tornado Cash

= Voyager Chapter = 

Joint Letter Regarding Potential Violations of the Federal Deposit Insurance Act

= FTX Chapter =

Securities and Exchange Commission v. Ellison et al

CFTC v. Bankman-Fried et al.

= Celsius Chapter = 

Celsius Network LLC, et al.

Examiner Report on CELSIUS NETWORK LLC, et al.

= Exchanges and Anti-Money Laundering Chapter =

Founder and Majority Owner of Cryptocurrency Exchange Bitzlato Charged

Consent Order in the matter of Coinbase, Inc.

= Stablecoins =

Tether

Terraform & Kwon (Kwonzi Scheme)



