
= Bitcoin Chapter =

Bitcoin White Paper

Wright vs. McCormack

Chapter 2

= Initial Coin Offerings Chapter =

When Howey Met Gary

SEC Charges Eleven Individuals in $300 Million Crypto Pyramid Scheme

SEC vs. LBRY

In the Matter of Zachary Coburn

Securities and Exchange Commission v. Ellison et al

CoinDeal Charged with Fraud

SEC v. Genesis & Gemini

In the Matter of Nexo Capital Inc.

Payward Ventures and Payward Trading

Terraform & Kwon (Kwonzi Scheme)

= Cryptocurrency and NFT Insider Trading Chapter =

Former Employee of NFT Marketplace Charged in First Ever Digital Asset Insider Trading Scheme

Founder and Majority Owner of Cryptocurrency Exchange Bitzlato Charged

Former Coinbase Insider Pleads Guilty In First-Ever Cryptocurrency Insider Trading Case

= Currency Mixers Chapter =

U.S. Treasury Issues First-Ever Sanctions on a Virtual Currency Mixer, Targets DPRK Cyber Threats

= Celsius Chapter =

Celsius Memos to the Community

Chapter 7 FDIC

Joint Letter Regarding Potential Violations of the Federal Deposit Insurance Act

= FTX Chapter =

CFTC v. Bankman-Fried et al.

= Celsius Chapter = 

Celsius Network LLC, et al.

Examiner Report on CELSIUS NETWORK LLC, et al.

Chapter 10 Anti-Money Laundering

Consent Order in the matter of Coinbase, Inc.

= Supplementary Materials =

Chapter 11 Ethics

ACCEPTING CRYPTOCURRENCY AS AN ADVANCE FEE FOR LEGAL SERVICES


